//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace template.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GIOHANG
    {
        QLBanSachEntity db = new QLBanSachEntity();
        public int iMasp { get; set; }
        public string sTensp { get; set; }
        public string sAnhBia { get; set; }
        public Nullable<decimal> dDonGia { get; set; }
        public int iSoLuong { get; set; }
        public Nullable<decimal> ThanhTien
        {
            get { return iSoLuong * dDonGia; }
        }
        public GIOHANG(int Masp)
        {
            iMasp = Masp;
            SACH sp = db.SACHes.Single(n => n.MaSach == iMasp);
            sTensp = sp.TenSach;
            sAnhBia = sp.HinhMinhHoa;
            dDonGia = decimal.Parse(sp.DonGia.ToString());
            iSoLuong = 1;
        }
    }
}
